FROM debian:buster-slim

SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

RUN apt-get update -qq && \
    apt-get install -yq wget && \
    wget -P /usr/share/keyrings \
    https://www.pllab.riec.tohoku.ac.jp/smlsharp/download/debian/dists/buster/smlsharp-archive-keyring.gpg && \
    wget -P /etc/apt/sources.list.d \
    https://www.pllab.riec.tohoku.ac.jp/smlsharp/download/debian/dists/buster/smlsharp.list && \
    apt-get update -qq && \
    apt-get install -y --no-install-recommends smlsharp && \
    apt-get purge -y wget && \
    apt-get autopurge -y && \
    rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    truncate -s 0 /var/log/**/*log

CMD ["smlsharp"]
