# syntax=docker/dockerfile:1.3-labs
FROM debian:buster-slim

ARG smlsharp_version="3.7.1"
ARG sources_url="https://www.pllab.riec.tohoku.ac.jp/smlsharp/download/debian/dists/buster/smlsharp.list"


SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

RUN <<EOF
  apt-get update -qq
  apt-get install -yq wget
  wget -P /usr/share/keyrings \
  https://www.pllab.riec.tohoku.ac.jp/smlsharp/download/debian/dists/buster/smlsharp-archive-keyring.gpg
  wget -P /etc/apt/sources.list.d \
  $sources_url
  apt-get update -qq
  apt-get install -y --no-install-recommends smlsharp=$smlsharp_version*
  apt-get purge -y wget
  apt-get autopurge -y
  rm -rf /var/cache/apt/archives/*
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
  truncate -s 0 /var/log/**/*log
EOF

CMD ["smlsharp"]
